#!/bin/bash

# install requires libraries
sudo add-apt-repository ppa:docky-core/ppa
sudo apt-get update -qq
sudo apt-get install -y bzr libgio2.0-cil-dev automake bzr mono-gmcs libmono-cairo2.0-cil gtk-sharp2 libndesk-dbus-glib1.0-cil libndesk-dbus1.0-cil libgtk2.0-dev libnotify0.4-cil libgio2.0-cil-dev libtool intltool ca-certificates gnome-desktop-sharp2 libgconf2-dev monodevelop-nunit
sudo apt-get build-dep -y docky

# fix link in maverick (test)
if [ "$(lsb_release -c -s)" == "maverick" ]; then
   sudo touch /var/lib/apt/lists/ppa.launchpad.net_savoirfairelinux_ppa_ubuntu_dists_maverick_main_source_Sources
fi

# build docky stacks
cd /tmp
bzr branch lp:~docky-core/docky/stacks
cd stacks
./autogen.sh 
./configure --prefix=/usr
make
sudo make install
killall docky
nohup docky > /dev/null &
